; SMB sv8 - Sio, vfd, 8inch

FDMEDIA         .EQU    FDM111          ; FDM720, FDM144, FDM360, FDM120 (ONLY RELEVANT IF FDENABLE = TRUE)
FDMEDIAALT      .EQU    FDM111          ; ALTERNATE MEDIA TO TRY, SAME CHOICES AS ABOVE (ONLY RELEVANT IF FDMAUTO = TRUE)
FDMAUTO         .EQU    FALSE           ; SELECT BETWEEN MEDIA OPTS ABOVE AUTOMATICALLY

FDSPECIAL       .EQU    FALSE            ; Use special mode instead oF AT/ESA mode

VFDTERMENABLE   .EQU    TRUE	; Enable VFD Terminal
